export const GET_ALL = 'GET_ALL'
export const SET_USER = 'SET_USER'
export const SET_USERS = 'SET_USERS'
export const GET_USER = 'GET_USER'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_FILTERS = 'SET_FILTERS'
export const SET_UPDATING_IMAGE = 'SET_UPDATING_IMAGE'
